"""creating models

Revision ID: 0a5a491a39d1
Revises: 
Create Date: 2024-06-11 04:48:31.263509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '0a5a491a39d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_password', sqlalchemy_utils.types.password.PasswordType(), nullable=False),
    sa.Column('_full_name', sa.String(length=30), nullable=False),
    sa.Column('_email', sa.String(length=50), nullable=False),
    sa.Column('_department', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_email'),
    sa.UniqueConstraint('_id')
    )
    op.create_table('client',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_full_name', sa.String(length=30), nullable=False),
    sa.Column('_email', sa.String(length=50), nullable=False),
    sa.Column('_telephone', sa.Integer(), nullable=False),
    sa.Column('_business_name', sa.String(), nullable=False),
    sa.Column('_creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_commercial_contact', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_commercial_contact'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_email'),
    sa.UniqueConstraint('_id'),
    sa.UniqueConstraint('_telephone')
    )
    op.create_table('contract',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_client_infos', sa.Integer(), nullable=False),
    sa.Column('_commercial', sa.Integer(), nullable=False),
    sa.Column('_total_amount', sa.Integer(), nullable=False),
    sa.Column('_left_amount', sa.Integer(), nullable=False),
    sa.Column('_creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['_client_infos'], ['client._id'], ),
    sa.ForeignKeyConstraint(['_commercial'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id')
    )
    op.create_table('event',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_contract_id', sa.Integer(), nullable=False),
    sa.Column('_client', sa.Integer(), nullable=False),
    sa.Column('_event_start', sa.String(), nullable=False),
    sa.Column('_event_end', sa.String(), nullable=False),
    sa.Column('_support_contact', sa.Integer(), nullable=False),
    sa.Column('_location', sa.String(), nullable=False),
    sa.Column('_attendees', sa.Integer(), nullable=False),
    sa.Column('_notes', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['_client'], ['client._id'], ),
    sa.ForeignKeyConstraint(['_contract_id'], ['contract._id'], ),
    sa.ForeignKeyConstraint(['_support_contact'], ['user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('contract')
    op.drop_table('client')
    op.drop_table('user')
    # ### end Alembic commands ###
