"""added event relationship

Revision ID: 0a96152eadee
Revises: daaed276d973
Create Date: 2024-06-14 14:46:29.669471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a96152eadee'
down_revision: Union[str, None] = 'daaed276d973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_client_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('client', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('event_client_fkey', 'event', 'client', ['client'], ['id'])
    # ### end Alembic commands ###
