"""added event support contact nullable

Revision ID: 0d0d4065dd93
Revises: 0a96152eadee
Create Date: 2024-06-17 17:39:00.400522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0d4065dd93'
down_revision: Union[str, None] = '0a96152eadee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'support_contact',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'support_contact',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
