"""deleted the last added relationship

Revision ID: 2b0ce535e1ac
Revises: e99b04f4f064
Create Date: 2024-06-13 15:37:51.910873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0ce535e1ac'
down_revision: Union[str, None] = 'e99b04f4f064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contract_commercial_fkey', 'contract', type_='foreignkey')
    op.drop_column('contract', 'commercial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('commercial', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('contract_commercial_fkey', 'contract', 'user', ['commercial'], ['id'])
    # ### end Alembic commands ###
