"""new start

Revision ID: 47a03b03eea1
Revises: 
Create Date: 2024-06-10 22:48:51.027771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a03b03eea1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('commercial', sa.Integer(), nullable=False))
    op.drop_constraint('client_commercial_contact_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'user', ['commercial'], ['id'])
    op.drop_column('client', 'commercial_contact')
    op.add_column('contract', sa.Column('commercial', sa.Integer(), nullable=False))
    op.drop_constraint('contract_commercial_id_fkey', 'contract', type_='foreignkey')
    op.create_foreign_key(None, 'contract', 'user', ['commercial'], ['id'])
    op.drop_column('contract', 'commercial_id')
    op.add_column('event', sa.Column('client', sa.Integer(), nullable=False))
    op.drop_constraint('event_client_infos_fkey', 'event', type_='foreignkey')
    op.drop_constraint('event_contract_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'client', ['client'], ['id'])
    op.drop_column('event', 'client_infos')
    op.drop_column('event', 'contract_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('client_infos', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_contract_id_fkey', 'event', 'contract', ['contract_id'], ['id'])
    op.create_foreign_key('event_client_infos_fkey', 'event', 'client', ['client_infos'], ['id'])
    op.drop_column('event', 'client')
    op.add_column('contract', sa.Column('commercial_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.create_foreign_key('contract_commercial_id_fkey', 'contract', 'user', ['commercial_id'], ['id'])
    op.drop_column('contract', 'commercial')
    op.add_column('client', sa.Column('commercial_contact', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_commercial_contact_fkey', 'client', 'user', ['commercial_contact'], ['id'])
    op.drop_column('client', 'commercial')
    # ### end Alembic commands ###
