"""editing contracts

Revision ID: 6893f6173256
Revises: 41b1683f66cb
Create Date: 2024-06-11 01:17:12.152604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6893f6173256'
down_revision: Union[str, None] = '41b1683f66cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('contract_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event', 'contract', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'contract_id')
    # ### end Alembic commands ###
