"""edited Role table

Revision ID: 6973098eda6e
Revises: 73e52ddf9c31
Create Date: 2024-06-11 14:36:02.953546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6973098eda6e'
down_revision: Union[str, None] = '73e52ddf9c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('role', 'name')
    # ### end Alembic commands ###
