"""added event name

Revision ID: daaed276d973
Revises: 2b0ce535e1ac
Create Date: 2024-06-13 21:26:17.096070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daaed276d973'
down_revision: Union[str, None] = '2b0ce535e1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('full_name', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'full_name')
    # ### end Alembic commands ###
